# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main


steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

variables:
- group: atari-app-variables
- name: dockerRegistryServiceConnection 
  value: 'Docker ACR'
- name:  imageRepository
  value: 'commodore/george-gannon-friday'
- name: containerRegistry
  value: 'YOURACR.azurecr.io'
- name: dockerfilePath
  value: '$(Build.SourcesDirectory)/Dockerfile'
- name: tag
  value: '$(Build.BuildId)'
- name: azureSubscription
  value: 'your-service-connector'
- name: appName
  value: 'acr-george-gannon'
pool:
  vmImage: 'ubuntu-latest'
stages:
- stage: Build
  displayName: 'Build and push Docker image'
  jobs:
  - job: Build
    displayName: 'Build'
    steps:
    - task: Docker@2
      displayName: 'Build and push'
    - task: Docker@2
      inputs:
        command: 'buildAndPush'
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
      env:
        DBTYPE: $(DBTYPE)
        DBHOST: $(DBHOST)
        DBNAME: $(DBNAME)
        DBUSER: $(DBUSER)
        DBPASSWORD: $(DBPASSWORD)
        DBSSLMODE: $(DBSSSLMODE)
- stage: Test
  displayName: 'Run tests'
  dependsOn: Build
  jobs:
  - job: Test
    displayName: 'Run tests'
    steps:
    - script: |
        cd learningAPI
        echo "Running tests..."
        go test ./...
      displayName: 'Run tests'
- stage: Deploy
  displayName: 'Deploy to Azure Web App'
  dependsOn: Test
  jobs:
  - job: Deploy
    displayName: 'Deploy Azure Web App'
    steps:
    - task: AzureWebAppContainer@1
      displayName: 'Azure Web App on Container Deploy'
      inputs:
        azureSubscription: 'Azure RM'
        appName: acr-george
        containers: acrbjssacademy.azurecr.io/commodore/george-friday:latest
      env:
        DBTYPE: $(DBTYPE)
        DBHOST: $(DBHOST)
        DBNAME: $(DBNAME)
        DBUSER: $(DBUSER)
        DBPASSWORD: $(DBPASSWORD)
        DBSSLMODE: $(DBSSSLMODE)
 
